name: Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  # lint:
  #   name: Lint code
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Configure node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: "18.x"

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Run ESLint
  #       run: npm run lint
  # unit-tests:
  #   name: Unit tests
  #   runs-on: ubuntu-latest
  #   needs: lint

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Configure node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: "18.x"

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Run unit tests
  #       run: npm run test:vitest
  install:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          # Disable running of tests within install job
          runTests: false
          build: npm run build

      - name: Save build folder
        uses: actions/upload-artifact@v4
        with:
          name: build
          if-no-files-found: error
          path: build

  cypress-run:
    runs-on: ubuntu-24.04
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download the build folder
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm run preview
          browser: chrome
