name: Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  # lint:
  #   name: Lint code
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Configure node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: "18.x"

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Run ESLint
  #       run: npm run lint
  # unit-tests:
  #   name: Unit tests
  #   runs-on: ubuntu-latest
  #   needs: lint

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Configure node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: "18.x"

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Run unit tests
  #       run: npm run test:vitest

  cypress-tests:
    name: Cypress e2e tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure node
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm install

      - name: Install wait-on
        run: npm install -g wait-on

      - name: Start application
        run: npm start &

      - name: Wait for app to be ready
        run: wait-on http://localhost:3000 --timeout 60000

      - name: Check running processes
        run: ps aux

      - name: Check open ports
        run: netstat -tlnp

      - name: Run Cypress tests
        run: npx cypress run --browser firefox --headless
